server:
  port: 3000

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-jolly-boat-a1eujht2.ap-southeast-1.aws.neon.tech/universityapp?sslmode=require}
    username: ${DB_USERNAME:universityapp_owner}
    password: ${DB_PASSWORD:cw9l6MhFIuJx}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jwt:
  access_token:
    sign_key: your_accesstoken_key111111111111111111111
    expiration: 3
  refresh_token:
    sign_key: your_accesstoken_key111111111111111111111
    expiration: 7

    

