server:
  port: 3000
  servlet:
    contextPath: /api/v1

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-tight-glitter-a17vbx2k-pooler.ap-southeast-1.aws.neon.tech/university-app?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_ARFzU8NZupg7}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  access_token:
    secret: your_accesstoken_key111111111111111111111
    expiry: 3
  refresh_token:
    secret: your_accesstoken_key111111111111111111111
    expiry: 7
logging:
  level:
    root: INFO
    com.universityapp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
admin:
  email: ${ADMIN_EMAIL:university_admin@hcmut.edu.vn}
  password: ${ADMIN_PASSWORD:university_admin}
  first_name: ${ADMIN_FIRSTNAME:university}
  last_name: ${ADMIN_LASTNAME:admin}
  phone_number: ${ADMIN_PHONENUMBER:0123456789}
