server:
  port: 3000

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.upvbjvqdkavexwpnpcxi.supabase.co:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:KxRpHkcGH2jqGrxj}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  # profiles:
  #   active: dev

    

